# Лабораторная работа 5
# Ансамбли моделей машинного обучения.
# Задание
1. Выберите набор данных (датасет) для решения задачи классификации или регресии.
2. В случае необходимости проведите удаление или заполнение пропусков и кодирование категориальных признаков.
3. С использованием метода train_test_split разделите выборку на обучающую и тестовую.
4. Обучите следующие ансамблевые модели:
  - две модели группы бэггинга (бэггинг или случайный лес или сверхслучайные деревья);
  - AdaBoost;
  - градиентный бустинг.
5. Оцените качество моделей с помощью одной из подходящих для задачи метрик. Сравните качество полученных моделей.

# Импорт бибилиотек

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
sns.set(style="ticks")
from sklearn.model_selection import train_test_split
from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score, recall_score, f1_score, classification_report
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier,GradientBoostingClassifier, StackingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline
from sklearn.svm import SVC

# Импорт данных

In [2]:
data = pd.read_csv('diabetes_binary_5050split_health_indicators_BRFSS2015.csv')

In [3]:
data.head()

,Diabetes_binary,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
0,0.0,1.0,0.0,1.0,26.0,0.0,0.0,0.0,1.0,0.0,...,1.0,0.0,3.0,5.0,30.0,0.0,1.0,4.0,6.0,8.0
1,0.0,1.0,1.0,1.0,26.0,1.0,1.0,0.0,0.0,1.0,...,1.0,0.0,3.0,0.0,0.0,0.0,1.0,12.0,6.0,8.0
2,0.0,0.0,0.0,1.0,26.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,1.0,0.0,10.0,0.0,1.0,13.0,6.0,8.0
3,0.0,1.0,1.0,1.0,28.0,1.0,0.0,0.0,1.0,1.0,...,1.0,0.0,3.0,0.0,3.0,0.0,1.0,11.0,6.0,8.0
4,0.0,0.0,0.0,1.0,29.0,1.0,0.0,0.0,1.0,1.0,...,1.0,0.0,2.0,0.0,0.0,0.0,0.0,8.0,5.0,8.0

# Обработка данных

Типы данных в представленном датасете:

In [4]:
data.dtypes

Diabetes_binary         float64
HighBP                  float64
HighChol                float64
CholCheck               float64
BMI                     float64
Smoker                  float64
Stroke                  float64
HeartDiseaseorAttack    float64
PhysActivity            float64
Fruits                  float64
Veggies                 float64
HvyAlcoholConsump       float64
AnyHealthcare           float64
NoDocbcCost             float64
GenHlth                 float64
MentHlth                float64
PhysHlth                float64
DiffWalk                float64
Sex                     float64
Age                     float64
Education               float64
Income                  float64
dtype: object

Проверим, есть ли в датасете пропущенные значения:

In [5]:
data.isnull().sum()

Diabetes_binary         0
HighBP                  0
HighChol                0
CholCheck               0
BMI                     0
Smoker                  0
Stroke                  0
HeartDiseaseorAttack    0
PhysActivity            0
Fruits                  0
Veggies                 0
HvyAlcoholConsump       0
AnyHealthcare           0
NoDocbcCost             0
GenHlth                 0
MentHlth                0
PhysHlth                0
DiffWalk                0
Sex                     0
Age                     0
Education               0
Income                  0
dtype: int64

В данном датасете нет строк или столбцов, содержащих пропущенные значения.

In [6]:
data.columns.tolist()

['Diabetes_binary',
 'HighBP',
 'HighChol',
 'CholCheck',
 'BMI',
 'Smoker',
 'Stroke',
 'HeartDiseaseorAttack',
 'PhysActivity',
 'Fruits',
 'Veggies',
 'HvyAlcoholConsump',
 'AnyHealthcare',
 'NoDocbcCost',
 'GenHlth',
 'MentHlth',
 'PhysHlth',
 'DiffWalk',
 'Sex',
 'Age',
 'Education',
 'Income']

In [7]:
data.head()

,Diabetes_binary,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
0,0.0,1.0,0.0,1.0,26.0,0.0,0.0,0.0,1.0,0.0,...,1.0,0.0,3.0,5.0,30.0,0.0,1.0,4.0,6.0,8.0
1,0.0,1.0,1.0,1.0,26.0,1.0,1.0,0.0,0.0,1.0,...,1.0,0.0,3.0,0.0,0.0,0.0,1.0,12.0,6.0,8.0
2,0.0,0.0,0.0,1.0,26.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,1.0,0.0,10.0,0.0,1.0,13.0,6.0,8.0
3,0.0,1.0,1.0,1.0,28.0,1.0,0.0,0.0,1.0,1.0,...,1.0,0.0,3.0,0.0,3.0,0.0,1.0,11.0,6.0,8.0
4,0.0,0.0,0.0,1.0,29.0,1.0,0.0,0.0,1.0,1.0,...,1.0,0.0,2.0,0.0,0.0,0.0,0.0,8.0,5.0,8.0

Проверим, содержатся ли в данных дубликаты:

In [8]:
print(data.duplicated())

0        False
1        False
2        False
3        False
4        False
         ...
70687    False
70688    False
70689    False
70690    False
70691    False
Length: 70692, dtype: bool

In [9]:
duplicate_rows = data[data.duplicated()]
print(duplicate_rows)

       Diabetes_binary  HighBP  HighChol  CholCheck   BMI  Smoker  Stroke  \
602                0.0     0.0       0.0        1.0  22.0     0.0     0.0
689                0.0     0.0       0.0        1.0  26.0     0.0     0.0
891                0.0     0.0       0.0        1.0  24.0     0.0     0.0
1092               0.0     0.0       0.0        1.0  21.0     0.0     0.0
1326               0.0     1.0       0.0        1.0  29.0     0.0     0.0
...                ...     ...       ...        ...   ...     ...     ...
69865              1.0     1.0       1.0        1.0  27.0     1.0     0.0
69939              1.0     1.0       1.0        1.0  27.0     1.0     0.0
70305              1.0     1.0       0.0        1.0  30.0     0.0     0.0
70591              1.0     1.0       1.0        1.0  30.0     0.0     0.0
70663              1.0     1.0       1.0        1.0  33.0     0.0     0.0

       HeartDiseaseorAttack  PhysActivity  Fruits  ...  AnyHealthcare  \
602                     0.0           1.0     1.0  ...            1.0
689                     0.0           1.0     1.0  ...            1.0
891                     0.0           1.0     1.0  ...            1.0
1092                    0.0           1.0     1.0  ...            1.0
1326                    0.0           1.0     0.0  ...            1.0
...                     ...           ...     ...  ...            ...
69865                   0.0           1.0     1.0  ...            1.0
69939                   0.0           1.0     1.0  ...            1.0
70305                   0.0           0.0     0.0  ...            1.0
70591                   1.0           1.0     1.0  ...            1.0
70663                   0.0           1.0     1.0  ...            1.0

       NoDocbcCost  GenHlth  MentHlth  PhysHlth  DiffWalk  Sex   Age  \
602            0.0      1.0       0.0       0.0       0.0  0.0   6.0
689            0.0      1.0       0.0       0.0       0.0  0.0   6.0
891            0.0      1.0       0.0       0.0       0.0  0.0   6.0
1092           0.0      1.0       0.0       0.0       0.0  0.0   5.0
1326           0.0      2.0       0.0       0.0       0.0  1.0  10.0
...            ...      ...       ...       ...       ...  ...   ...
69865          0.0      4.0       0.0       0.0       0.0  1.0  12.0
69939          0.0      3.0       0.0       0.0       0.0  1.0  12.0
70305          0.0      3.0       0.0       0.0       0.0  1.0   9.0
70591          0.0      2.0       0.0       0.0       0.0  1.0  10.0
70663          0.0      3.0       0.0       0.0       0.0  1.0   9.0

       Education  Income
602          6.0     8.0
689          6.0     8.0
891          6.0     8.0
1092         6.0     8.0
1326         5.0     6.0
...          ...     ...
69865        6.0     8.0
69939        6.0     8.0
70305        4.0     7.0
70591        6.0     8.0
70663        6.0     6.0

[1635 rows x 22 columns]

В данном датасете содержатся дубликаты. Удалим эти строки:

In [10]:
data = data.drop_duplicates()

In [11]:
print(data.duplicated())
duplicate_rows = data[data.duplicated()]
print(duplicate_rows)

0        False
1        False
2        False
3        False
4        False
         ...
70687    False
70688    False
70689    False
70690    False
70691    False
Length: 69057, dtype: bool
Empty DataFrame
Columns: [Diabetes_binary, HighBP, HighChol, CholCheck, BMI, Smoker, Stroke, HeartDiseaseorAttack, PhysActivity, Fruits, Veggies, HvyAlcoholConsump, AnyHealthcare, NoDocbcCost, GenHlth, MentHlth, PhysHlth, DiffWalk, Sex, Age, Education, Income]
Index: []

[0 rows x 22 columns]

Теперь дубликатов нет.

In [12]:
data['Income'].unique()

array([8., 7., 6., 3., 4., 1., 5., 2.])

In [13]:
le = LabelEncoder()
data['Income'] = le.fit_transform(data['Income'])

In [ ]:
data['Income'].unique()

array([7, 6, 5, 2, 3, 0, 4, 1])

# Разделение выборки на обучающую и тестовую

С использованием метода train_test_split разделим выборку на обучающую и тестовую:

In [ ]:
data.shape

(69057, 22)

In [ ]:
# Признаки без целевой переменной
x = data.drop('Diabetes_binary', axis=1)
x.head()

,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,Veggies,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
0,1.0,0.0,1.0,26.0,0.0,0.0,0.0,1.0,0.0,1.0,...,1.0,0.0,3.0,5.0,30.0,0.0,1.0,4.0,6.0,7
1,1.0,1.0,1.0,26.0,1.0,1.0,0.0,0.0,1.0,0.0,...,1.0,0.0,3.0,0.0,0.0,0.0,1.0,12.0,6.0,7
2,0.0,0.0,1.0,26.0,0.0,0.0,0.0,1.0,1.0,1.0,...,1.0,0.0,1.0,0.0,10.0,0.0,1.0,13.0,6.0,7
3,1.0,1.0,1.0,28.0,1.0,0.0,0.0,1.0,1.0,1.0,...,1.0,0.0,3.0,0.0,3.0,0.0,1.0,11.0,6.0,7
4,0.0,0.0,1.0,29.0,1.0,0.0,0.0,1.0,1.0,1.0,...,1.0,0.0,2.0,0.0,0.0,0.0,0.0,8.0,5.0,7

In [ ]:
# Целевая переменная
y = data['Diabetes_binary']
y.head()

0    0.0
1    0.0
2    0.0
3    0.0
4    0.0
Name: Diabetes_binary, dtype: float64

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)
#20% данных будут отложены для тестирования, а 80% будут использованы для обучения модели

In [ ]:
# Размер обучающей выборки
x_train.shape, y_train.shape

((55245, 21), (55245,))

In [ ]:
# Размер тестовой выборки
x_test.shape, y_test.shape

((13812, 21), (13812,))

# Обучение ансамблевых моделей

## Бэггинг

### Бэггинг

In [ ]:
model_bc = BaggingClassifier(n_estimators=200, oob_score=True, random_state=10)
model_bc.fit(x_train, y_train)

BaggingClassifier(n_estimators=200, oob_score=True, random_state=10)

### Случайный лес

In [ ]:
rand_forest_model = RandomForestClassifier(n_estimators=200, oob_score=True, random_state=10)
rand_forest_model.fit(x_train, y_train)

RandomForestClassifier(n_estimators=200, oob_score=True, random_state=10)

## AdaBoost

In [ ]:
ada_boost_model = AdaBoostClassifier(n_estimators=200, algorithm='SAMME', random_state=10)
ada_boost_model.fit(x_train, y_train)

/Users/jerry/BMSTU/ТМО/venv/lib/python3.13/site-packages/sklearn/ensemble/_weight_boosting.py:519: FutureWarning: The parameter 'algorithm' is deprecated in 1.6 and has no effect. It will be removed in version 1.8.
  warnings.warn(

AdaBoostClassifier(algorithm='SAMME', n_estimators=200, random_state=10)

## Градиентный бустинг

In [ ]:
grad_boost_model = GradientBoostingClassifier(n_estimators=200)
grad_boost_model.fit(x_train, y_train)

GradientBoostingClassifier(n_estimators=200)

In [ ]:
# Оценка качества моделей

In [ ]:
models = [model_bc, rand_forest_model, ada_boost_model, grad_boost_model, ]
for model in models:
    print(f"{type(model).__name__}:")
    print('\t',f"accuracy = {accuracy_score(y_test,model.predict(x_test))}")

BaggingClassifier:
	 accuracy = 0.7143064002316826
RandomForestClassifier:
	 accuracy = 0.7271937445699392
AdaBoostClassifier:
	 accuracy = 0.7460903562119896
GradientBoostingClassifier:
	 accuracy = 0.7458007529684333